version: '3.8'
services:
    cassandra-node1:
      container_name: cassandra_node_1
      image: cassandra:3.11
      networks:
        - dockernet
      environment:
        WAIT_TIMEOUT: "60"
        JVM_OPTS: "-Dcassandra.consistent.rangemovement=false"
        CASSANDRA_CLUSTER_NAME: "DemoCluster"
        CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
        CASSANDRA_DC: "DATA"
        restart: always 
      volumes:
        - /home/ronak/Documents/git-code/dockerCode/cassandra/store:/var/lib/cassandra
      ports:
        - "9042:9042"
    
    product-ms:
      container_name: product_service
      image: product-ms
      build:
        context: product-ms
        dockerfile: Dockerfile
      restart: always
      environment:
        - JAVA_OPTS= -DCASSANDRA_URI=cassandra -DCASSANDRA_PORT=9042 -DDATA_CENTER=DATA
      links:
        - cassandra-node1:cassandra
       
      restart: always
      networks:
        dockernet:
          ipv4_address: 172.16.2.11
      ports:
        - "8082:8082"


networks:
  dockernet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.2.0/24
      