spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RonakRabadiya/nineleaps-POC
          search-paths:
            - 'microservice-config-properties/global/{profile}'
            - 'microservice-config-properties/{application}/{profile}'
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}